#!/usr/bin/env bash
# adapters/test-to-opencode.sh — Failing test for to-opencode.sh (Step 4, test-first).
#
# Verifies that adapters/to-opencode.sh produces correct OpenCode output for
# the two reference agents: bitsmith (has opencode: block) and riskmancer
# (has opencode: block with disallowedTools handled in claude: block).
#
# Exit 0 = all tests passed
# Exit 1 = one or more tests failed
#
# Usage:
#   ./adapters/test-to-opencode.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ADAPTER="$SCRIPT_DIR/to-opencode.sh"

pass_count=0
fail_count=0

_pass() {
  echo "PASS: $1"
  pass_count=$((pass_count + 1))
}

_fail() {
  echo "FAIL: $1"
  echo "  detail: $2"
  fail_count=$((fail_count + 1))
}

# ---------------------------------------------------------------------------
# Prerequisite: adapter must exist and be executable
# ---------------------------------------------------------------------------
echo "--- Prerequisite checks ---"

if [ ! -f "$ADAPTER" ]; then
  _fail "adapter exists" "adapters/to-opencode.sh not found at $ADAPTER"
  echo ""
  echo "Results: $pass_count passed, $fail_count failed."
  exit 1
fi

if [ ! -x "$ADAPTER" ]; then
  _fail "adapter is executable" "adapters/to-opencode.sh is not executable"
  echo ""
  echo "Results: $pass_count passed, $fail_count failed."
  exit 1
fi

_pass "adapter exists and is executable"

# ---------------------------------------------------------------------------
# Clean up any previously generated output before testing --dry-run
# ---------------------------------------------------------------------------
rm -rf "$REPO_ROOT/opencode/agents" "$REPO_ROOT/opencode/AGENTS.md"

# ---------------------------------------------------------------------------
# Run adapter in --dry-run mode; capture output for inspection
# ---------------------------------------------------------------------------
echo ""
echo "--- --dry-run produces output ---"

dry_output="$("$ADAPTER" --dry-run 2>&1)"

if [ -z "$dry_output" ]; then
  _fail "--dry-run produces output" "got empty output"
else
  _pass "--dry-run produces output"
fi

# --dry-run must not write files
if [ -d "$REPO_ROOT/opencode/agents" ] && ls "$REPO_ROOT/opencode/agents/"*.md >/dev/null 2>&1; then
  _fail "--dry-run does not write files" "opencode/agents/*.md found after --dry-run"
else
  _pass "--dry-run does not write files"
fi

# ---------------------------------------------------------------------------
# Run adapter (write mode) into a temp directory by temporarily overriding
# OUT_DIR via environment variable (if the adapter supports it), or by
# running in normal mode and inspecting the real output directory.
# ---------------------------------------------------------------------------
echo ""
echo "--- Write mode produces output files ---"

"$ADAPTER"

OPENCODE_DIR="$REPO_ROOT/opencode"
AGENTS_DIR="$OPENCODE_DIR/agents"

if [ ! -d "$AGENTS_DIR" ]; then
  _fail "opencode/agents/ directory created" "directory not found: $AGENTS_DIR"
  echo ""
  echo "Results: $pass_count passed, $fail_count failed."
  exit 1
fi

_pass "opencode/agents/ directory created"

BITSMITH_OUT="$AGENTS_DIR/bitsmith.md"
RISKMANCER_OUT="$AGENTS_DIR/riskmancer.md"
AGENTS_MD="$OPENCODE_DIR/AGENTS.md"

if [ ! -f "$BITSMITH_OUT" ]; then
  _fail "bitsmith.md generated" "file not found: $BITSMITH_OUT"
else
  _pass "bitsmith.md generated"
fi

if [ ! -f "$RISKMANCER_OUT" ]; then
  _fail "riskmancer.md generated" "file not found: $RISKMANCER_OUT"
else
  _pass "riskmancer.md generated"
fi

if [ ! -f "$AGENTS_MD" ]; then
  _fail "opencode/AGENTS.md generated" "file not found: $AGENTS_MD"
else
  _pass "opencode/AGENTS.md generated"
fi

# ---------------------------------------------------------------------------
# Validate bitsmith.md output
# ---------------------------------------------------------------------------
echo ""
echo "--- bitsmith.md output validation ---"

if [ -f "$BITSMITH_OUT" ]; then
  bitsmith_content=$(cat "$BITSMITH_OUT")

  # Must have generated header
  if echo "$bitsmith_content" | grep -q "Generated by ai-tpk adapters"; then
    _pass "bitsmith.md has generated header"
  else
    _fail "bitsmith.md has generated header" "header comment not found"
  fi

  # Must have anthropic/ model prefix
  if echo "$bitsmith_content" | grep -q "model: anthropic/"; then
    _pass "bitsmith.md model has anthropic/ prefix"
  else
    _fail "bitsmith.md model has anthropic/ prefix" "model: anthropic/ not found in output"
  fi

  # Must NOT have 'name:' key in frontmatter
  if echo "$bitsmith_content" | grep -q "^name:"; then
    _fail "bitsmith.md has no 'name:' key" "found 'name:' key in frontmatter"
  else
    _pass "bitsmith.md has no 'name:' key"
  fi

  # Must NOT have 'tools:' key in frontmatter
  if echo "$bitsmith_content" | grep -q "^tools:"; then
    _fail "bitsmith.md has no 'tools:' key" "found 'tools:' key in frontmatter"
  else
    _pass "bitsmith.md has no 'tools:' key"
  fi

  # Must NOT have 'share:' key
  if echo "$bitsmith_content" | grep -q "^share:"; then
    _fail "bitsmith.md has no 'share:' key" "found 'share:' key in frontmatter"
  else
    _pass "bitsmith.md has no 'share:' key"
  fi

  # Must NOT have 'provider:' key
  if echo "$bitsmith_content" | grep -q "^provider:"; then
    _fail "bitsmith.md has no 'provider:' key" "found 'provider:' key in frontmatter"
  else
    _pass "bitsmith.md has no 'provider:' key"
  fi

  # Must have 'permission:' as YAML array (lines starting with '- ')
  if echo "$bitsmith_content" | grep -q "permission:"; then
    _pass "bitsmith.md has permission field"
  else
    _fail "bitsmith.md has permission field" "permission: not found"
  fi

  if echo "$bitsmith_content" | grep -q "^  - "; then
    _pass "bitsmith.md permission is YAML array format"
  else
    _fail "bitsmith.md permission is YAML array format" "no '  - ' array items found"
  fi

  # Agent tool must NOT appear in permission (no opencode equivalent)
  if echo "$bitsmith_content" | grep -q "  - agent"; then
    _fail "bitsmith.md has no 'agent' in permission" "found '  - agent' in permission array"
  else
    _pass "bitsmith.md has no 'agent' in permission"
  fi

  # Must have mode: subagent (from opencode: block)
  if echo "$bitsmith_content" | grep -q "^mode: subagent"; then
    _pass "bitsmith.md has mode: subagent"
  else
    _fail "bitsmith.md has mode: subagent" "mode: subagent not found"
  fi

  # description must be present
  if echo "$bitsmith_content" | grep -q "^description:"; then
    _pass "bitsmith.md has description"
  else
    _fail "bitsmith.md has description" "description: not found"
  fi
fi

# ---------------------------------------------------------------------------
# Validate riskmancer.md output
# ---------------------------------------------------------------------------
echo ""
echo "--- riskmancer.md output validation ---"

if [ -f "$RISKMANCER_OUT" ]; then
  riskmancer_content=$(cat "$RISKMANCER_OUT")

  # Must have anthropic/ model prefix (opus model)
  if echo "$riskmancer_content" | grep -q "model: anthropic/claude-opus"; then
    _pass "riskmancer.md model has anthropic/claude-opus prefix"
  else
    _fail "riskmancer.md model has anthropic/claude-opus prefix" "not found in output"
  fi

  # Must have permission field
  if echo "$riskmancer_content" | grep -q "permission:"; then
    _pass "riskmancer.md has permission field"
  else
    _fail "riskmancer.md has permission field" "permission: not found"
  fi

  # disallowedTools (Write, Edit) must NOT appear in permission
  if echo "$riskmancer_content" | grep -q "  - write"; then
    _fail "riskmancer.md excludes 'write' (disallowedTools)" "found '  - write' in permission array"
  else
    _pass "riskmancer.md excludes 'write' (disallowedTools)"
  fi

  if echo "$riskmancer_content" | grep -q "  - edit"; then
    _fail "riskmancer.md excludes 'edit' (disallowedTools)" "found '  - edit' in permission array"
  else
    _pass "riskmancer.md excludes 'edit' (disallowedTools)"
  fi

  # Must NOT have 'name:' key
  if echo "$riskmancer_content" | grep -q "^name:"; then
    _fail "riskmancer.md has no 'name:' key" "found 'name:' key"
  else
    _pass "riskmancer.md has no 'name:' key"
  fi

  # Must NOT have 'disallowedTools:' key (Claude-only field)
  if echo "$riskmancer_content" | grep -q "^disallowedTools:"; then
    _fail "riskmancer.md has no 'disallowedTools:' key" "found disallowedTools: in output"
  else
    _pass "riskmancer.md has no 'disallowedTools:' key"
  fi

  # Must NOT have 'trigger_keywords:' key (Claude-only field)
  if echo "$riskmancer_content" | grep -q "^trigger_keywords:"; then
    _fail "riskmancer.md has no 'trigger_keywords:' key" "found trigger_keywords: in output"
  else
    _pass "riskmancer.md has no 'trigger_keywords:' key"
  fi

  # Must NOT have 'level:' key (Claude-only field)
  if echo "$riskmancer_content" | grep -q "^level:"; then
    _fail "riskmancer.md has no 'level:' key" "found level: in output"
  else
    _pass "riskmancer.md has no 'level:' key"
  fi
fi

# ---------------------------------------------------------------------------
# Validate AGENTS.md
# ---------------------------------------------------------------------------
echo ""
echo "--- opencode/AGENTS.md validation ---"

if [ -f "$AGENTS_MD" ]; then
  agents_md_content=$(cat "$AGENTS_MD")

  if echo "$agents_md_content" | grep -q "Generated by ai-tpk adapters"; then
    _pass "AGENTS.md has generated header"
  else
    _fail "AGENTS.md has generated header" "header comment not found"
  fi

  if echo "$agents_md_content" | grep -q "bitsmith"; then
    _pass "AGENTS.md lists bitsmith agent"
  else
    _fail "AGENTS.md lists bitsmith agent" "bitsmith not mentioned"
  fi

  if echo "$agents_md_content" | grep -q "riskmancer"; then
    _pass "AGENTS.md lists riskmancer agent"
  else
    _fail "AGENTS.md lists riskmancer agent" "riskmancer not mentioned"
  fi
fi

# ---------------------------------------------------------------------------
# Idempotency check
# ---------------------------------------------------------------------------
echo ""
echo "--- Idempotency ---"

first_run_checksum=$(md5 -q "$BITSMITH_OUT" 2>/dev/null || md5sum "$BITSMITH_OUT" | awk '{print $1}')
"$ADAPTER"
second_run_checksum=$(md5 -q "$BITSMITH_OUT" 2>/dev/null || md5sum "$BITSMITH_OUT" | awk '{print $1}')

if [ "$first_run_checksum" = "$second_run_checksum" ]; then
  _pass "adapter is idempotent (bitsmith.md same on second run)"
else
  _fail "adapter is idempotent (bitsmith.md same on second run)" "checksums differ: $first_run_checksum vs $second_run_checksum"
fi

# ---------------------------------------------------------------------------
# Results
# ---------------------------------------------------------------------------
echo ""
echo "Results: $pass_count passed, $fail_count failed."
if [ "$fail_count" -gt 0 ]; then
  exit 1
fi
exit 0
