#!/usr/bin/env -S deno run --allow-read --allow-write
// adapters/to-claude.ts — Transform src/agents/*.md into claude/agents/*.md
// (Claude Code format).
//
// Usage:
//   ./adapters/to-claude.ts            # Write files to claude/agents/
//   ./adapters/to-claude.ts --dry-run  # Print what would be generated; do not write files

import { join } from "@std/path";
import {
  agentNameFromFile,
  extractFrontmatter,
  getArray,
  getBody,
  getNamespacedField,
} from "./lib/parse.ts";
import type { AgentSource, ClaudeBlock } from "./types.ts";

const SCRIPT_DIR = import.meta.dirname!;
const REPO_ROOT = join(SCRIPT_DIR, "..");

const GENERATED_HEADER =
  "<!-- Generated by ai-tpk adapters. Do not edit directly. -->";

// ---------------------------------------------------------------------------
// buildClaudeFrontmatter
//
// Constructs the Claude Code YAML frontmatter string for a given agent.
// Emits only fields that are present (non-null, non-empty).
// Field order matches the bash adapter exactly:
//   name, description, model, level, disallowedTools, mandatory,
//   trigger_keywords, invoke_when, tools
// ---------------------------------------------------------------------------
function buildClaudeFrontmatter(
  frontmatter: AgentSource,
  name: string,
): string {
  const lines: string[] = [];

  const description = frontmatter.description;
  const model = frontmatter.model;

  const level = getNamespacedField<ClaudeBlock, "level">(
    frontmatter,
    "claude",
    "level",
  );
  const disallowedTools = getNamespacedField<ClaudeBlock, "disallowedTools">(
    frontmatter,
    "claude",
    "disallowedTools",
  );
  const mandatory = getNamespacedField<ClaudeBlock, "mandatory">(
    frontmatter,
    "claude",
    "mandatory",
  );
  const invokeWhen = getNamespacedField<ClaudeBlock, "invoke_when">(
    frontmatter,
    "claude",
    "invoke_when",
  );
  const tools = getNamespacedField<ClaudeBlock, "tools">(
    frontmatter,
    "claude",
    "tools",
  );

  const triggerKeywords = getArray(frontmatter, "claude.trigger_keywords");

  // Build inline JSON array for trigger_keywords: ["kw1", "kw2", ...]
  let triggerKeywordsInline = "";
  if (triggerKeywords.length > 0) {
    const items = triggerKeywords
      .map((kw) => `"${kw.replace(/"/g, '\\"')}"`)
      .join(", ");
    triggerKeywordsInline = `[${items}]`;
  }

  lines.push(`name: ${name}`);

  if (description) {
    lines.push(`description: "${description.replace(/"/g, '\\"')}"`);
  }

  if (model) {
    lines.push(`model: ${model}`);
  }

  if (level !== undefined && level !== null) {
    lines.push(`level: ${level}`);
  }

  if (disallowedTools) {
    lines.push(`disallowedTools: ${disallowedTools}`);
  }

  if (mandatory !== undefined && mandatory !== null) {
    lines.push(`mandatory: ${mandatory}`);
  }

  if (triggerKeywordsInline) {
    lines.push(`trigger_keywords: ${triggerKeywordsInline}`);
  }

  if (invokeWhen) {
    lines.push(`invoke_when: "${invokeWhen.replace(/"/g, '\\"')}"`);
  }

  if (tools) {
    lines.push(`tools: "${tools}"`);
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// generateClaudeAgent
//
// Produces the full content of a Claude Code agent file for the given source
// file path. Returns the complete file content as a string.
// Exported so tests can call it directly.
// ---------------------------------------------------------------------------
export async function generateClaudeAgent(filePath: string): Promise<string> {
  const name = agentNameFromFile(filePath);
  const frontmatter = await extractFrontmatter(filePath);
  const body = await getBody(filePath);
  const fm = buildClaudeFrontmatter(frontmatter, name);

  // Strip trailing newlines from body (matching bash command-substitution behaviour)
  // then add exactly one trailing newline, as bash's `printf '%s\n'` does.
  const normalizedBody = body.replace(/\n+$/, "") + "\n";
  return `${GENERATED_HEADER}\n\n---\n${fm}\n---\n${normalizedBody}`;
}

// ---------------------------------------------------------------------------
// Main — only runs when the script is invoked directly (not imported)
// ---------------------------------------------------------------------------
if (import.meta.main) {
  const dryRun = Deno.args.includes("--dry-run");
  const unknownArgs = Deno.args.filter((a) => a !== "--dry-run");
  if (unknownArgs.length > 0) {
    console.error(`Unknown argument(s): ${unknownArgs.join(", ")}`);
    console.error("Usage: to-claude.ts [--dry-run]");
    Deno.exit(1);
  }

  const srcDir = join(REPO_ROOT, "src", "agents");
  const outDir = join(REPO_ROOT, "claude", "agents");

  // Verify source directory exists
  try {
    await Deno.stat(srcDir);
  } catch {
    console.error(`ERROR: Source directory not found: ${srcDir}`);
    Deno.exit(1);
  }

  // Ensure output directory exists (unless dry-run)
  if (!dryRun) {
    await Deno.mkdir(outDir, { recursive: true });
  }

  // Collect and sort source files for deterministic output
  const srcFiles: string[] = [];
  for await (const entry of Deno.readDir(srcDir)) {
    if (entry.isFile && entry.name.endsWith(".md")) {
      srcFiles.push(join(srcDir, entry.name));
    }
  }

  if (srcFiles.length === 0) {
    console.warn(`WARNING: No source agent files found in ${srcDir}`);
    Deno.exit(0);
  }

  srcFiles.sort();

  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    const outFile = join(outDir, `${name}.md`);
    const content = await generateClaudeAgent(srcFile);

    if (dryRun) {
      console.log(`=== Would write: ${outFile} ===`);
      console.log(content);
      console.log("");
    } else {
      await Deno.writeTextFile(outFile, content);
      console.log(`Written: ${outFile}`);
    }
  }
}
