#!/usr/bin/env bash
# adapters/to-claude.sh — Transform src/agents/*.md into claude/agents/*.md (Claude Code format).
#
# Usage:
#   ./adapters/to-claude.sh            # Write files to claude/agents/
#   ./adapters/to-claude.sh --dry-run  # Print what would be generated; do not write files
#
# Requires: yq (checked via adapters/lib/parse.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source shared parsing library (handles yq check at source time)
# shellcheck source=lib/parse.sh
source "$SCRIPT_DIR/lib/parse.sh"

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
fi

GENERATED_HEADER="<!-- Generated by ai-tpk adapters. Do not edit directly. -->"
SRC_DIR="$REPO_ROOT/src/agents"
OUT_DIR="$REPO_ROOT/claude/agents"

if [ ! -d "$SRC_DIR" ]; then
  echo "ERROR: Source directory not found: $SRC_DIR" >&2
  exit 1
fi

if [ "$DRY_RUN" = false ] && [ ! -d "$OUT_DIR" ]; then
  mkdir -p "$OUT_DIR"
fi

# ---------------------------------------------------------------------------
# build_claude_frontmatter <file> <name>
#
# Constructs the Claude Code YAML frontmatter for a given source agent file.
# Prints only fields that are present (non-empty / non-null).
# ---------------------------------------------------------------------------
build_claude_frontmatter() {
  local file="$1" name="$2"

  # Universal fields
  local description model
  description=$(get_field "$file" description)
  model=$(get_field "$file" model)

  # Claude-specific fields
  local tools level disallowed_tools mandatory invoke_when
  tools=$(get_namespaced_field "$file" claude tools)
  level=$(get_namespaced_field "$file" claude level)
  disallowed_tools=$(get_namespaced_field "$file" claude disallowedTools)
  mandatory=$(get_namespaced_field "$file" claude mandatory)
  invoke_when=$(get_namespaced_field "$file" claude invoke_when)

  # trigger_keywords is a YAML array — collect into inline JSON array format
  local trigger_keywords_raw trigger_keywords_inline
  trigger_keywords_raw=$(get_array "$file" claude.trigger_keywords)

  if [ -n "$trigger_keywords_raw" ]; then
    # Build the inline JSON array: ["elem1", "elem2", ...]
    trigger_keywords_inline=$(
      echo "$trigger_keywords_raw" | awk '
        BEGIN { printf "[" }
        NR > 1 { printf ", " }
        { gsub(/"/, "\\\""); printf "\"" $0 "\"" }
        END { printf "]" }
      '
    )
  else
    trigger_keywords_inline=""
  fi

  # Emit frontmatter — only fields that are present.
  # Fields that contain spaces, commas, or special characters are quoted.
  echo "name: $name"

  if [ -n "$description" ]; then
    echo "description: \"${description//\"/\\\"}\""
  fi

  if [ -n "$model" ]; then
    echo "model: $model"
  fi

  if [ -n "$level" ]; then
    echo "level: $level"
  fi

  if [ -n "$disallowed_tools" ]; then
    echo "disallowedTools: $disallowed_tools"
  fi

  if [ -n "$mandatory" ]; then
    echo "mandatory: $mandatory"
  fi

  if [ -n "$trigger_keywords_inline" ]; then
    echo "trigger_keywords: $trigger_keywords_inline"
  fi

  if [ -n "$invoke_when" ]; then
    echo "invoke_when: \"${invoke_when//\"/\\\"}\""
  fi

  if [ -n "$tools" ]; then
    echo "tools: \"$tools\""
  fi
}

# ---------------------------------------------------------------------------
# generate_agent_output <file>
#
# Produces the full content of a Claude Code agent file for the given source.
# Prints to stdout.
# ---------------------------------------------------------------------------
generate_agent_output() {
  local file="$1"
  local name
  name=$(agent_name_from_file "$file")

  local frontmatter body
  frontmatter=$(build_claude_frontmatter "$file" "$name")
  body=$(get_body "$file")

  printf '%s\n' "$GENERATED_HEADER"
  printf '\n'
  printf '%s\n' "---"
  printf '%s\n' "$frontmatter"
  printf '%s\n' "---"
  printf '%s\n' "$body"
}

# ---------------------------------------------------------------------------
# Main loop — iterate over all source agent files
# ---------------------------------------------------------------------------
shopt -s nullglob
src_files=("$SRC_DIR"/*.md)

if [ ${#src_files[@]} -eq 0 ]; then
  echo "WARNING: No source agent files found in $SRC_DIR" >&2
  exit 0
fi

for src_file in "${src_files[@]}"; do
  name=$(agent_name_from_file "$src_file")
  out_file="$OUT_DIR/$name.md"

  if [ "$DRY_RUN" = true ]; then
    echo "=== Would write: $out_file ==="
    generate_agent_output "$src_file"
    echo ""
  else
    generate_agent_output "$src_file" > "$out_file"
    echo "Written: $out_file"
  fi
done
