// adapters/to-claude_test.ts — Tests for the Claude Code adapter.
//
// Verifies structural correctness of generateClaudeAgent() output.
// No reliance on committed baseline files — tests run on a clean checkout.

import { assert, assertEquals, assertMatch, assertNotMatch } from "@std/assert";
import { exists } from "@std/fs";
import { join } from "@std/path";
import { generateClaudeAgent } from "./to-claude.ts";

const REPO_ROOT = join(import.meta.dirname!, "..");
const SRC_DIR = join(REPO_ROOT, "src", "agents");

// ---------------------------------------------------------------------------
// bitsmith: structural checks — has header, name, description, non-empty body
// ---------------------------------------------------------------------------
Deno.test("generateClaudeAgent bitsmith has generated header", async () => {
  const srcFile = join(SRC_DIR, "bitsmith.md");
  const generated = await generateClaudeAgent(srcFile);

  assertMatch(
    generated,
    /<!-- Generated by ai-tpk adapters\. Do not edit directly\. -->/,
    "must contain generated header comment",
  );
});

Deno.test(
  "generateClaudeAgent bitsmith has name: bitsmith in frontmatter",
  async () => {
    const srcFile = join(SRC_DIR, "bitsmith.md");
    const generated = await generateClaudeAgent(srcFile);

    assertMatch(
      generated,
      /^name: bitsmith$/m,
      "must contain 'name: bitsmith'",
    );
  },
);

Deno.test(
  "generateClaudeAgent bitsmith has non-empty description",
  async () => {
    const srcFile = join(SRC_DIR, "bitsmith.md");
    const generated = await generateClaudeAgent(srcFile);

    assertMatch(
      generated,
      /^description: ".+"/m,
      "must contain non-empty description",
    );
  },
);

Deno.test("generateClaudeAgent bitsmith has non-empty body", async () => {
  const srcFile = join(SRC_DIR, "bitsmith.md");
  const generated = await generateClaudeAgent(srcFile);

  // Extract body after closing ---
  const lines = generated.split("\n");
  let delimCount = 0;
  let bodyStart = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i] === "---") {
      delimCount++;
      if (delimCount === 2) {
        bodyStart = i + 1;
        break;
      }
    }
  }
  assert(bodyStart !== -1, "must have closing --- delimiter");
  const body = lines.slice(bodyStart).join("\n");
  assert(body.trim().length > 0, "body after frontmatter must be non-empty");
});

Deno.test(
  "generateClaudeAgent bitsmith does not have invoke_when",
  async () => {
    const srcFile = join(SRC_DIR, "bitsmith.md");
    const generated = await generateClaudeAgent(srcFile);

    assertNotMatch(
      generated,
      /^invoke_when:/m,
      "bitsmith must not contain 'invoke_when:'",
    );
  },
);

// ---------------------------------------------------------------------------
// riskmancer: has trigger_keywords (inline JSON array) and invoke_when
// ---------------------------------------------------------------------------
Deno.test(
  "generateClaudeAgent riskmancer trigger_keywords is inline JSON array",
  async () => {
    const srcFile = join(SRC_DIR, "riskmancer.md");
    const generated = await generateClaudeAgent(srcFile);

    // Must match: trigger_keywords: ["kw1", "kw2", ...]
    assertMatch(
      generated,
      /^trigger_keywords: \[".+"\]/m,
      "trigger_keywords must be inline JSON array",
    );
  },
);

Deno.test("generateClaudeAgent riskmancer has invoke_when", async () => {
  const srcFile = join(SRC_DIR, "riskmancer.md");
  const generated = await generateClaudeAgent(srcFile);

  assertMatch(
    generated,
    /^invoke_when: "/m,
    "riskmancer must have invoke_when",
  );
});

Deno.test(
  "generateClaudeAgent riskmancer has name: riskmancer",
  async () => {
    const srcFile = join(SRC_DIR, "riskmancer.md");
    const generated = await generateClaudeAgent(srcFile);

    assertMatch(
      generated,
      /^name: riskmancer$/m,
      "must contain 'name: riskmancer'",
    );
  },
);

// ---------------------------------------------------------------------------
// All agents: structural correctness loop
// ---------------------------------------------------------------------------
Deno.test(
  "generateClaudeAgent - all agents have correct structure",
  async () => {
    for await (const entry of Deno.readDir(SRC_DIR)) {
      if (!entry.name.endsWith(".md")) continue;
      const srcPath = join(SRC_DIR, entry.name);
      const agentName = entry.name.replace(/\.md$/, "");
      const generated = await generateClaudeAgent(srcPath);

      // Header present
      assert(
        generated.includes(
          "<!-- Generated by ai-tpk adapters. Do not edit directly. -->",
        ),
        `${agentName}: missing generated header`,
      );

      // name: field matches filename-derived name
      assert(
        /^name: /m.test(generated),
        `${agentName}: frontmatter must contain 'name:' field`,
      );
      assert(
        generated.includes(`name: ${agentName}`),
        `${agentName}: name field must match filename-derived name`,
      );

      // description: field present and non-empty
      assert(
        /^description: ".+"/m.test(generated),
        `${agentName}: must have non-empty description`,
      );

      // Non-empty body after closing ---
      const lines = generated.split("\n");
      let delimCount = 0;
      let bodyStart = -1;
      for (let i = 0; i < lines.length; i++) {
        if (lines[i] === "---") {
          delimCount++;
          if (delimCount === 2) {
            bodyStart = i + 1;
            break;
          }
        }
      }
      assert(
        bodyStart !== -1,
        `${agentName}: must have closing --- delimiter`,
      );
      const body = lines.slice(bodyStart).join("\n");
      assert(
        body.trim().length > 0,
        `${agentName}: body must be non-empty`,
      );
    }
  },
);

// ---------------------------------------------------------------------------
// Idempotency: running generateClaudeAgent twice produces identical output
// ---------------------------------------------------------------------------
Deno.test("generateClaudeAgent is idempotent", async () => {
  const srcFile = join(SRC_DIR, "riskmancer.md");
  const first = await generateClaudeAgent(srcFile);
  const second = await generateClaudeAgent(srcFile);
  assertEquals(first, second);
});

// ---------------------------------------------------------------------------
// dry-run: prints to stdout without creating files
// ---------------------------------------------------------------------------
Deno.test("--dry-run prints output and does not create files", async () => {
  const outFile = join(REPO_ROOT, "claude", "agents", "bitsmith.md");

  // Remove the output file if it exists, so we can verify dry-run doesn't create it
  try {
    await Deno.remove(outFile);
  } catch {
    // File doesn't exist — that's fine
  }

  // Run the adapter script with --dry-run
  const cmd = new Deno.Command("deno", {
    args: [
      "run",
      "--allow-read",
      "--allow-write",
      join(import.meta.dirname!, "to-claude.ts"),
      "--dry-run",
    ],
    stdout: "piped",
    stderr: "piped",
  });
  const result = await cmd.output();
  assertEquals(result.code, 0, "dry-run should exit 0");

  // stdout should contain agent content for bitsmith
  const stdout = new TextDecoder().decode(result.stdout);
  assert(
    stdout.includes("name: bitsmith"),
    "stdout should contain bitsmith frontmatter",
  );
  assert(
    stdout.includes("=== Would write:"),
    "stdout should contain dry-run header",
  );

  // The output file must NOT exist after dry-run
  const fileExists = await exists(outFile);
  assertEquals(fileExists, false, "dry-run must not create output files");
});
