#!/usr/bin/env bash
# adapters/to-opencode.sh — Transform src/agents/*.md into opencode/agents/*.md (OpenCode format).
#
# Usage:
#   ./adapters/to-opencode.sh            # Write files to opencode/agents/ and opencode/AGENTS.md
#   ./adapters/to-opencode.sh --dry-run  # Print what would be generated; do not write files
#
# Requires: yq (checked via adapters/lib/parse.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source shared parsing library (handles yq check at source time)
# shellcheck source=lib/parse.sh
source "$SCRIPT_DIR/lib/parse.sh"

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
fi

GENERATED_HEADER="<!-- Generated by ai-tpk adapters. Do not edit directly. -->"
SRC_DIR="$REPO_ROOT/src/agents"
OUT_DIR="$REPO_ROOT/opencode/agents"
AGENTS_MD="$REPO_ROOT/opencode/AGENTS.md"

if [ ! -d "$SRC_DIR" ]; then
  echo "ERROR: Source directory not found: $SRC_DIR" >&2
  exit 1
fi

if [ "$DRY_RUN" = false ]; then
  mkdir -p "$OUT_DIR"
fi

# ---------------------------------------------------------------------------
# has_opencode_block <file>
#
# Returns 0 (true) if the file has an opencode: block in its frontmatter.
# ---------------------------------------------------------------------------
has_opencode_block() {
  local file="$1"
  local result
  result=$(_extract_yaml "$file" | yq ".opencode" 2>/dev/null)
  if [ -z "$result" ] || [ "$result" = "null" ]; then
    return 1
  fi
  return 0
}

# ---------------------------------------------------------------------------
# tool_uses_delegation <file>
#
# Returns 0 (true) if the agent's claude.tools string contains "Agent" or
# "Task", indicating heavy use of Agent/Task tool delegation.
# ---------------------------------------------------------------------------
tool_uses_delegation() {
  local file="$1"
  local tools
  tools=$(get_namespaced_field "$file" claude tools)
  if echo "$tools" | grep -qwE "(Agent|Task)"; then
    return 0
  fi
  return 1
}

# ---------------------------------------------------------------------------
# build_permission_from_claude_tools <file>
#
# Best-effort fallback: reads claude.tools, lowercases each tool, omits
# "Agent" (no OpenCode equivalent), and also omits any tools listed in
# claude.disallowedTools.
#
# Prints each permitted tool on its own line.
# ---------------------------------------------------------------------------
build_permission_from_claude_tools() {
  local file="$1"

  local tools_str disallowed_str
  tools_str=$(get_namespaced_field "$file" claude tools)
  disallowed_str=$(get_namespaced_field "$file" claude disallowedTools)

  # Split disallowedTools into a newline-separated list, lowercase
  local disallowed_list=""
  if [ -n "$disallowed_str" ]; then
    disallowed_list=$(echo "$disallowed_str" | tr ', ' '\n' | tr '[:upper:]' '[:lower:]' | grep -v '^$' || true)
  fi

  if [ -z "$tools_str" ]; then
    return 0
  fi

  # Split tools_str by ", " and process each
  echo "$tools_str" | tr ', ' '\n' | grep -v '^$' | while IFS= read -r tool; do
    local tool_lower
    tool_lower=$(echo "$tool" | tr '[:upper:]' '[:lower:]')

    # Omit "agent" — no OpenCode equivalent
    if [ "$tool_lower" = "agent" ]; then
      continue
    fi

    # Omit tools in disallowedTools
    if echo "$disallowed_list" | grep -qx "$tool_lower"; then
      continue
    fi

    echo "$tool_lower"
  done
}

# ---------------------------------------------------------------------------
# build_opencode_frontmatter <file>
#
# Constructs the OpenCode YAML frontmatter for a given source agent file.
# Emits ONLY valid OpenCode keys:
#   description, model (anthropic/-prefixed), mode, permission (array),
#   temperature, top_p, color, steps
# ---------------------------------------------------------------------------
build_opencode_frontmatter() {
  local file="$1"

  # Universal fields
  local description model_raw model
  description=$(get_field "$file" description)
  model_raw=$(get_field "$file" model)
  model=$(map_model_opencode "$model_raw")

  # Emit description
  if [ -n "$description" ]; then
    echo "description: \"${description//\"/\\\"}\""
  fi

  # Emit model
  if [ -n "$model" ]; then
    echo "model: $model"
  fi

  if has_opencode_block "$file"; then
    # --- Primary path: opencode: block exists ---

    local mode temperature top_p color steps
    mode=$(get_namespaced_field "$file" opencode mode)
    temperature=$(get_namespaced_field "$file" opencode temperature)
    top_p=$(get_namespaced_field "$file" opencode top_p)
    color=$(get_namespaced_field "$file" opencode color)
    steps=$(get_namespaced_field "$file" opencode steps)

    if [ -n "$mode" ]; then
      echo "mode: $mode"
    fi

    # permission: YAML array
    local perms
    perms=$(get_array "$file" opencode.permission)
    if [ -n "$perms" ]; then
      echo "permission:"
      while IFS= read -r perm; do
        echo "  - $perm"
      done <<< "$perms"
    fi

    if [ -n "$temperature" ]; then
      echo "temperature: $temperature"
    fi

    if [ -n "$top_p" ]; then
      echo "top_p: $top_p"
    fi

    if [ -n "$color" ]; then
      echo "color: $color"
    fi

    if [ -n "$steps" ]; then
      echo "steps: $steps"
    fi

  else
    # --- Fallback path: no opencode: block — best-effort from claude: block ---
    # Always set mode: subagent in fallback
    echo "mode: subagent"

    local perms
    perms=$(build_permission_from_claude_tools "$file")
    if [ -n "$perms" ]; then
      echo "permission:"
      while IFS= read -r perm; do
        echo "  - $perm"
      done <<< "$perms"
    fi
  fi
}

# ---------------------------------------------------------------------------
# generate_agent_output <file>
#
# Produces the full content of an OpenCode agent file for the given source.
# Prints to stdout.
# ---------------------------------------------------------------------------
generate_agent_output() {
  local file="$1"

  local frontmatter body
  frontmatter=$(build_opencode_frontmatter "$file")
  body=$(get_body "$file")

  printf '%s\n' "$GENERATED_HEADER"
  printf '\n'
  printf '%s\n' "---"
  printf '%s\n' "$frontmatter"
  printf '%s\n' "---"

  # Emit Agent/Task delegation warning for agents that use the Agent tool.
  # Each comment is preceded by a blank line.
  if tool_uses_delegation "$file"; then
    printf '\n'
    printf '%s\n' "<!-- NOTE: This agent relies on Agent/Task tool delegation which has no OpenCode equivalent. Sub-agent orchestration will not function as in Claude Code. -->"
  fi

  # Emit best-effort warning if no opencode: block was found.
  if ! has_opencode_block "$file"; then
    printf '\n'
    printf '%s\n' "<!-- NOTE: No opencode: block found in source. Best-effort generation from claude: block. -->"
  fi

  # The body begins with a blank line (from get_body preserving the separator).
  # That blank line ensures exactly one blank line between the last header element and the body.
  printf '%s\n' "$body"
}

# ---------------------------------------------------------------------------
# generate_agents_md
#
# Produces the content of opencode/AGENTS.md — global instructions for
# OpenCode users. Lists each agent's name and description dynamically.
# Prints to stdout.
# ---------------------------------------------------------------------------
generate_agents_md() {
  printf '%s\n' "$GENERATED_HEADER"
  printf '\n'
  cat << 'HEADER_CONTENT'
# AI TPK — OpenCode Global Instructions

This file provides global instructions for OpenCode users of the AI TPK agent team.

## Agent Team

AI TPK provides a D&D-themed multi-agent team with 11 specialized agents. Each agent is defined in `.opencode/agents/` (project-level) or `~/.config/opencode/agents/` (global).

## Available Agents

HEADER_CONTENT

  shopt -s nullglob
  local agent_files=("$SRC_DIR"/*.md)
  for src_file in "${agent_files[@]}"; do
    local name description
    name=$(agent_name_from_file "$src_file")
    description=$(get_field "$src_file" description)
    printf '%s\n' "- **${name}** — ${description}"
  done

  cat << 'FOOTER_CONTENT'

## Important Notes

- **Orchestration**: The DungeonMaster agent coordinates work, but sub-agent delegation via the `Agent` tool is a Claude Code-specific feature. In OpenCode, use agents directly rather than through DungeonMaster orchestration.
- **Skills**: Skills (commit-message-guide, open-pull-request) are Claude Code-specific features and are not available in OpenCode.
- **Hooks**: Session logging hooks (talekeeper) are Claude Code-specific and are not available in OpenCode.
- **Session logs**: The Talekeeper session chronicle system is not available in OpenCode.

## Usage

Select an agent by typing `@agentname` in OpenCode to invoke it directly.
FOOTER_CONTENT
}

# ---------------------------------------------------------------------------
# Main loop — iterate over all source agent files
# ---------------------------------------------------------------------------
shopt -s nullglob
src_files=("$SRC_DIR"/*.md)

if [ ${#src_files[@]} -eq 0 ]; then
  echo "WARNING: No source agent files found in $SRC_DIR" >&2
  exit 0
fi

for src_file in "${src_files[@]}"; do
  name=$(agent_name_from_file "$src_file")
  out_file="$OUT_DIR/$name.md"

  if [ "$DRY_RUN" = true ]; then
    echo "=== Would write: $out_file ==="
    generate_agent_output "$src_file"
    echo ""
  else
    generate_agent_output "$src_file" > "$out_file"
    echo "Written: $out_file"
  fi
done

# Generate opencode/AGENTS.md
if [ "$DRY_RUN" = true ]; then
  echo "=== Would write: $AGENTS_MD ==="
  generate_agents_md
  echo ""
else
  generate_agents_md > "$AGENTS_MD"
  echo "Written: $AGENTS_MD"
fi
