#!/usr/bin/env -S deno run --allow-read --allow-write
// adapters/to-opencode.ts — Transform src/agents/*.md into opencode/agents/*.md
// (OpenCode format).
//
// Usage:
//   ./adapters/to-opencode.ts            # Write files to opencode/agents/ and opencode/AGENTS.md
//   ./adapters/to-opencode.ts --dry-run  # Print what would be generated; do not write files

import { join } from "@std/path";
import {
  agentNameFromFile,
  extractFrontmatter,
  getArray,
  getBody,
  getNamespacedField,
  mapModelOpencode,
} from "./lib/parse.ts";
import type { AgentSource, ClaudeBlock, OpencodeBlock } from "./types.ts";

const SCRIPT_DIR = import.meta.dirname!;
const REPO_ROOT = join(SCRIPT_DIR, "..");

const GENERATED_HEADER =
  "<!-- Generated by ai-tpk adapters. Do not edit directly. -->";

const DELEGATION_NOTE =
  "<!-- NOTE: This agent relies on Agent/Task tool delegation which has no OpenCode equivalent. Sub-agent orchestration will not function as in Claude Code. -->";

const BEST_EFFORT_NOTE =
  "<!-- NOTE: No opencode: block found in source. Best-effort generation from claude: block. -->";

// ---------------------------------------------------------------------------
// hasOpencodeBlock
//
// Returns true if the parsed frontmatter has a non-null opencode block.
// ---------------------------------------------------------------------------
export function hasOpencodeBlock(frontmatter: AgentSource): boolean {
  return frontmatter.opencode !== undefined && frontmatter.opencode !== null;
}

// ---------------------------------------------------------------------------
// toolUsesDelegation
//
// Returns true if the agent's claude.tools string contains "Agent" or "Task"
// as whole words, indicating use of Agent/Task tool delegation.
// ---------------------------------------------------------------------------
export function toolUsesDelegation(frontmatter: AgentSource): boolean {
  const tools = getNamespacedField<ClaudeBlock, "tools">(
    frontmatter,
    "claude",
    "tools",
  );
  if (!tools) {
    return false;
  }
  return /\b(Agent|Task)\b/.test(tools);
}

// ---------------------------------------------------------------------------
// buildPermissionFromClaudeTools
//
// Best-effort fallback: reads claude.tools, lowercases each tool, omits
// "agent" (no OpenCode equivalent), and also omits any tools listed in
// claude.disallowedTools.
//
// Returns an array of permitted tool names.
// ---------------------------------------------------------------------------
export function buildPermissionFromClaudeTools(
  frontmatter: AgentSource,
): string[] {
  const toolsStr = getNamespacedField<ClaudeBlock, "tools">(
    frontmatter,
    "claude",
    "tools",
  );
  const disallowedStr = getNamespacedField<ClaudeBlock, "disallowedTools">(
    frontmatter,
    "claude",
    "disallowedTools",
  );

  if (!toolsStr) {
    return [];
  }

  // Build set of disallowed tool names (lowercase)
  const disallowedSet = new Set<string>();
  if (disallowedStr) {
    for (const part of disallowedStr.split(",")) {
      const trimmed = part.trim().toLowerCase();
      if (trimmed) {
        disallowedSet.add(trimmed);
      }
    }
  }

  // Split tools string by ", " and filter
  const result: string[] = [];
  for (const tool of toolsStr.split(",")) {
    const trimmed = tool.trim();
    if (!trimmed) continue;
    const lower = trimmed.toLowerCase();
    if (lower === "agent") continue;
    if (disallowedSet.has(lower)) continue;
    result.push(lower);
  }

  return result;
}

// ---------------------------------------------------------------------------
// buildOpencodeFrontmatter
//
// Constructs the OpenCode YAML frontmatter string for a given agent.
// Emits ONLY valid OpenCode keys: description, model (with anthropic/ prefix),
// mode, permission (YAML array), temperature, top_p, color, steps.
// ---------------------------------------------------------------------------
export function buildOpencodeFrontmatter(frontmatter: AgentSource): string {
  const lines: string[] = [];

  const description = frontmatter.description;
  const model = mapModelOpencode(frontmatter.model);

  if (description) {
    lines.push(`description: "${description.replace(/"/g, '\\"')}"`);
  }

  if (model) {
    lines.push(`model: ${model}`);
  }

  if (hasOpencodeBlock(frontmatter)) {
    // Primary path: opencode: block exists

    const mode = getNamespacedField<OpencodeBlock, "mode">(
      frontmatter,
      "opencode",
      "mode",
    );
    const temperature = getNamespacedField<OpencodeBlock, "temperature">(
      frontmatter,
      "opencode",
      "temperature",
    );
    const top_p = getNamespacedField<OpencodeBlock, "top_p">(
      frontmatter,
      "opencode",
      "top_p",
    );
    const color = getNamespacedField<OpencodeBlock, "color">(
      frontmatter,
      "opencode",
      "color",
    );
    const steps = getNamespacedField<OpencodeBlock, "steps">(
      frontmatter,
      "opencode",
      "steps",
    );

    if (mode) {
      lines.push(`mode: ${mode}`);
    }

    const perms = getArray(frontmatter, "opencode.permission");
    if (perms.length > 0) {
      lines.push("permission:");
      for (const perm of perms) {
        lines.push(`  - ${perm}`);
      }
    }

    if (temperature !== undefined && temperature !== null) {
      lines.push(`temperature: ${temperature}`);
    }

    if (top_p !== undefined && top_p !== null) {
      lines.push(`top_p: ${top_p}`);
    }

    if (color !== undefined && color !== null) {
      lines.push(`color: ${color}`);
    }

    if (steps !== undefined && steps !== null) {
      lines.push(`steps: ${steps}`);
    }
  } else {
    // Fallback path: no opencode: block — best-effort from claude: block
    // Always set mode: subagent in fallback
    lines.push("mode: subagent");

    const perms = buildPermissionFromClaudeTools(frontmatter);
    if (perms.length > 0) {
      lines.push("permission:");
      for (const perm of perms) {
        lines.push(`  - ${perm}`);
      }
    }
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// generateAgentOutput
//
// Produces the full content of an OpenCode agent file for the given source
// file path. Returns the complete file content as a string.
// Exported so tests can call it directly.
// ---------------------------------------------------------------------------
export async function generateAgentOutput(filePath: string): Promise<string> {
  const frontmatter = await extractFrontmatter(filePath);
  const body = await getBody(filePath);
  const fm = buildOpencodeFrontmatter(frontmatter);

  const usesDelegation = toolUsesDelegation(frontmatter);
  const hasOpencode = hasOpencodeBlock(frontmatter);

  // Build the content parts.
  // The body from getBody starts with "\n" (the blank line in the source file
  // after the closing ---). We prepend an extra "\n" when appending body so
  // that the separator is always a blank line, matching bash's
  // `printf '%s\n' "$body"` which outputs "\n<body>" (body already starts
  // with \n). Notes each contribute their own "\n\n...\n" chunk and the body's
  // leading "\n" provides the blank line after the last note.
  let content = `${GENERATED_HEADER}\n\n---\n${fm}\n---`;

  if (usesDelegation) {
    content += `\n\n${DELEGATION_NOTE}`;
  }

  if (!hasOpencode) {
    content += `\n\n${BEST_EFFORT_NOTE}`;
  }

  // Strip trailing newlines from body (matching bash command-substitution
  // behaviour) then add exactly one trailing newline.
  const normalizedBody = body.replace(/\n+$/, "") + "\n";

  // Append "\n" + body so that:
  //   - no notes: "---\n" + "\n<body>" = "---\n\n<body>" (blank line after ---)
  //   - with note: "NOTE\n" + "\n<body>" = "NOTE\n\n<body>" (blank line after note)
  // The body itself starts with "\n" (the source's blank line after ---), so
  // we get the correct double-newline separation in both cases.
  content += "\n" + normalizedBody;

  return content;
}

// ---------------------------------------------------------------------------
// generateAgentsMd
//
// Produces the content of opencode/AGENTS.md — global instructions for
// OpenCode users. Lists each agent's name and description dynamically.
// Exported so tests can call it directly.
// ---------------------------------------------------------------------------
export async function generateAgentsMd(srcDir: string): Promise<string> {
  // Collect and sort source files for deterministic output
  const srcFiles: string[] = [];
  for await (const entry of Deno.readDir(srcDir)) {
    if (entry.isFile && entry.name.endsWith(".md")) {
      srcFiles.push(join(srcDir, entry.name));
    }
  }
  srcFiles.sort();

  const agentLines: string[] = [];
  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    const frontmatter = await extractFrontmatter(srcFile);
    const description = frontmatter.description;
    agentLines.push(`- **${name}** — ${description}`);
  }

  const header = `${GENERATED_HEADER}

# AI TPK — OpenCode Global Instructions

This file provides global instructions for OpenCode users of the AI TPK agent team.

## Agent Team

AI TPK provides a D&D-themed multi-agent team with 11 specialized agents. Each agent is defined in \`.opencode/agents/\` (project-level) or \`~/.config/opencode/agents/\` (global).

## Available Agents

${agentLines.join("\n")}

## Important Notes

- **Orchestration**: The DungeonMaster agent coordinates work, but sub-agent delegation via the \`Agent\` tool is a Claude Code-specific feature. In OpenCode, use agents directly rather than through DungeonMaster orchestration.
- **Skills**: Skills (commit-message-guide, open-pull-request) are Claude Code-specific features and are not available in OpenCode.
- **Hooks**: Session logging hooks (talekeeper) are Claude Code-specific and are not available in OpenCode.
- **Session logs**: The Talekeeper session chronicle system is not available in OpenCode.

## Usage

Select an agent by typing \`@agentname\` in OpenCode to invoke it directly.
`;

  return header;
}

// ---------------------------------------------------------------------------
// Main — only runs when the script is invoked directly (not imported)
// ---------------------------------------------------------------------------
if (import.meta.main) {
  const dryRun = Deno.args.includes("--dry-run");
  const unknownArgs = Deno.args.filter((a) => a !== "--dry-run");
  if (unknownArgs.length > 0) {
    console.error(`Unknown argument(s): ${unknownArgs.join(", ")}`);
    console.error("Usage: to-opencode.ts [--dry-run]");
    Deno.exit(1);
  }

  const srcDir = join(REPO_ROOT, "src", "agents");
  const outDir = join(REPO_ROOT, "opencode", "agents");
  const agentsMdPath = join(REPO_ROOT, "opencode", "AGENTS.md");

  // Verify source directory exists
  try {
    await Deno.stat(srcDir);
  } catch {
    console.error(`ERROR: Source directory not found: ${srcDir}`);
    Deno.exit(1);
  }

  // Ensure output directory exists (unless dry-run)
  if (!dryRun) {
    await Deno.mkdir(outDir, { recursive: true });
  }

  // Collect and sort source files for deterministic output
  const srcFiles: string[] = [];
  for await (const entry of Deno.readDir(srcDir)) {
    if (entry.isFile && entry.name.endsWith(".md")) {
      srcFiles.push(join(srcDir, entry.name));
    }
  }

  if (srcFiles.length === 0) {
    console.warn(`WARNING: No source agent files found in ${srcDir}`);
    Deno.exit(0);
  }

  srcFiles.sort();

  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    const outFile = join(outDir, `${name}.md`);
    const content = await generateAgentOutput(srcFile);

    if (dryRun) {
      console.log(`=== Would write: ${outFile} ===`);
      console.log(content);
      console.log("");
    } else {
      await Deno.writeTextFile(outFile, content);
      console.log(`Written: ${outFile}`);
    }
  }

  // Generate opencode/AGENTS.md
  const agentsMdContent = await generateAgentsMd(srcDir);
  if (dryRun) {
    console.log(`=== Would write: ${agentsMdPath} ===`);
    console.log(agentsMdContent);
    console.log("");
  } else {
    await Deno.writeTextFile(agentsMdPath, agentsMdContent);
    console.log(`Written: ${agentsMdPath}`);
  }
}
