#!/usr/bin/env -S deno run --allow-read --allow-write
// adapters/validate.ts — Verify that adapter output is structurally correct.
//
// Imports adapter logic directly (no subprocess) to regenerate all output,
// then checks each generated file for required structure, allowed keys,
// and completeness. No git commands are used.
//
// Usage:
//   ./adapters/validate.ts

import { join } from "@std/path";
import { agentNameFromFile } from "./lib/parse.ts";
import { generateClaudeAgent } from "./to-claude.ts";
import { generateAgentOutput, generateAgentsMd } from "./to-opencode.ts";

const SCRIPT_DIR = import.meta.dirname!;
const REPO_ROOT = join(SCRIPT_DIR, "..");

const GENERATED_HEADER =
  "<!-- Generated by ai-tpk adapters. Do not edit directly. -->";

// Keys allowed in OpenCode frontmatter (must stay in sync with src/FORMAT.md)
const OPENCODE_ALLOWED_KEYS = new Set([
  "description",
  "model",
  "mode",
  "permission",
  "temperature",
  "top_p",
  "color",
  "steps",
]);

// Keys that must NOT appear in OpenCode frontmatter
const OPENCODE_FORBIDDEN_KEYS = [
  "name",
  "share",
  "provider",
  "tools",
  "level",
  "disallowedTools",
  "mandatory",
  "trigger_keywords",
  "invoke_when",
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Parse frontmatter from generated file content.
 * Returns an object mapping key -> raw value string (before YAML parsing).
 * Only looks at the first frontmatter block (between the first pair of ---).
 */
function parseFrontmatterKeys(content: string): Set<string> {
  const lines = content.split("\n");
  const keys = new Set<string>();
  let inFrontmatter = false;
  let delimCount = 0;

  for (const line of lines) {
    if (line === "---") {
      delimCount++;
      if (delimCount === 1) {
        inFrontmatter = true;
        continue;
      } else if (delimCount === 2) {
        break;
      }
    }
    if (inFrontmatter && delimCount === 1) {
      // Match top-level YAML keys (no leading spaces)
      const match = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*):/);
      if (match) {
        keys.add(match[1]);
      }
    }
  }
  return keys;
}

/**
 * Extract the body after the closing --- delimiter.
 * Returns the text after the second --- line.
 */
function extractBody(content: string): string {
  const lines = content.split("\n");
  let delimCount = 0;
  let bodyStart = -1;

  for (let i = 0; i < lines.length; i++) {
    if (lines[i] === "---") {
      delimCount++;
      if (delimCount === 2) {
        bodyStart = i + 1;
        break;
      }
    }
  }

  if (bodyStart === -1) return "";
  return lines.slice(bodyStart).join("\n");
}

// ---------------------------------------------------------------------------
// Main validate function
// ---------------------------------------------------------------------------

export async function validate(): Promise<void> {
  const srcDir = join(REPO_ROOT, "src", "agents");
  const claudeOutDir = join(REPO_ROOT, "claude", "agents");
  const opencodeOutDir = join(REPO_ROOT, "opencode", "agents");
  const agentsMdPath = join(REPO_ROOT, "opencode", "AGENTS.md");

  const errors: string[] = [];

  // ---------------------------------------------------------------------------
  // Collect source agent files
  // ---------------------------------------------------------------------------
  const srcFiles: string[] = [];
  for await (const entry of Deno.readDir(srcDir)) {
    if (entry.isFile && entry.name.endsWith(".md")) {
      srcFiles.push(join(srcDir, entry.name));
    }
  }
  srcFiles.sort();

  if (srcFiles.length === 0) {
    console.error(`ERROR: No source agent files found in ${srcDir}`);
    Deno.exit(1);
  }

  // ---------------------------------------------------------------------------
  // Ensure output directories exist
  // ---------------------------------------------------------------------------
  await Deno.mkdir(claudeOutDir, { recursive: true });
  await Deno.mkdir(opencodeOutDir, { recursive: true });

  // ---------------------------------------------------------------------------
  // Regenerate and check Claude Code agent files
  // ---------------------------------------------------------------------------
  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    const outFile = join(claudeOutDir, `${name}.md`);
    const content = await generateClaudeAgent(srcFile);
    await Deno.writeTextFile(outFile, content);

    const prefix = `claude/agents/${name}.md`;

    // Must start with generated header
    if (!content.startsWith(GENERATED_HEADER)) {
      errors.push(`${prefix}: missing generated header comment`);
    }

    // Must have name: field
    const keys = parseFrontmatterKeys(content);
    if (!keys.has("name")) {
      errors.push(`${prefix}: frontmatter missing required key 'name'`);
    }

    // Must have description: field
    if (!keys.has("description")) {
      errors.push(`${prefix}: frontmatter missing required key 'description'`);
    }

    // Body after closing --- must be non-empty (not just whitespace)
    const body = extractBody(content);
    if (body.trim() === "") {
      errors.push(`${prefix}: body after frontmatter is empty`);
    }
  }

  // ---------------------------------------------------------------------------
  // Regenerate and check OpenCode agent files
  // ---------------------------------------------------------------------------
  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    const outFile = join(opencodeOutDir, `${name}.md`);
    const content = await generateAgentOutput(srcFile);
    await Deno.writeTextFile(outFile, content);

    const prefix = `opencode/agents/${name}.md`;

    // Must start with generated header
    if (!content.startsWith(GENERATED_HEADER)) {
      errors.push(`${prefix}: missing generated header comment`);
    }

    const keys = parseFrontmatterKeys(content);

    // Must not contain forbidden keys
    for (const forbidden of OPENCODE_FORBIDDEN_KEYS) {
      if (keys.has(forbidden)) {
        errors.push(
          `${prefix}: frontmatter contains forbidden key '${forbidden}'`,
        );
      }
    }

    // Must only contain allowed keys
    for (const key of keys) {
      if (!OPENCODE_ALLOWED_KEYS.has(key)) {
        errors.push(
          `${prefix}: frontmatter contains unknown key '${key}' (not in allowed set)`,
        );
      }
    }

    // Body after closing --- must be non-empty
    const body = extractBody(content);
    if (body.trim() === "") {
      errors.push(`${prefix}: body after frontmatter is empty`);
    }
  }

  // ---------------------------------------------------------------------------
  // Regenerate and check opencode/AGENTS.md
  // ---------------------------------------------------------------------------
  const agentsMdContent = await generateAgentsMd(srcDir);
  await Deno.writeTextFile(agentsMdPath, agentsMdContent);

  if (!agentsMdContent.includes(GENERATED_HEADER)) {
    errors.push("opencode/AGENTS.md: missing generated header comment");
  }

  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);
    if (!agentsMdContent.includes(`**${name}**`)) {
      errors.push(`opencode/AGENTS.md: missing agent entry '**${name}**'`);
    }
  }

  // ---------------------------------------------------------------------------
  // Completeness: every src/agents/*.md must have output in both harnesses
  // ---------------------------------------------------------------------------
  for (const srcFile of srcFiles) {
    const name = agentNameFromFile(srcFile);

    try {
      await Deno.stat(join(claudeOutDir, `${name}.md`));
    } catch {
      errors.push(
        `Completeness: claude/agents/${name}.md missing after generation`,
      );
    }

    try {
      await Deno.stat(join(opencodeOutDir, `${name}.md`));
    } catch {
      errors.push(
        `Completeness: opencode/agents/${name}.md missing after generation`,
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Report results
  // ---------------------------------------------------------------------------
  if (errors.length > 0) {
    console.error(`✗ Validation failed with ${errors.length} error(s):`);
    for (const err of errors) {
      console.error(`  - ${err}`);
    }
    Deno.exit(1);
  } else {
    console.log(
      `✓ All ${srcFiles.length} agents validated successfully (both harnesses)`,
    );
  }
}

if (import.meta.main) {
  await validate();
}
